# Generated by Django 3.1.3 on 2020-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201120_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MBTI',
            field=models.IntegerField(choices=[(1, 'ESTJ'), (2, 'ESTP'), (3, 'ESFJ'), (4, 'ESFP'), (5, 'ENTJ'), (6, 'ENTP'), (7, 'ENFJ'), (8, 'ENFP'), (9, 'ISTJ'), (10, 'ISTP'), (11, 'ISFJ'), (12, 'ISFP'), (13, 'INTJ'), (14, 'INTP'), (15, 'INFJ'), (16, 'INFP')]),
        ),
    ]
