# Generated by Django 3.1.3 on 2020-11-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitys', '0002_remove_review_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rank',
        ),
    ]
