# Generated by Django 3.1.3 on 2020-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=50)),
                ('pubDate', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=200)),
                ('userRating', models.FloatField()),
            ],
        ),
    ]
