# Generated by Django 3.1.3 on 2020-11-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.IntegerField()),
                ('overview', models.CharField(max_length=500)),
                ('release_date', models.CharField(max_length=50)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField()),
                ('poster_path', models.CharField(max_length=200)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=100)),
                ('genre_ids', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
