# Generated by Django 3.1.3 on 2020-11-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.FloatField()),
                ('overview', models.CharField(max_length=500, null=True)),
                ('release_date', models.CharField(max_length=50)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField()),
                ('poster_path', models.CharField(max_length=200)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('original_language', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=100)),
                ('genre_ids', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_movie_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
