# Generated by Django 3.1.3 on 2020-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201120_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.FloatField(),
        ),
    ]
